command: [
  "streamlit",
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "sql-warehouse"
  - name: DATABRICKS_DASHBOARD_URL
    value: "https://<your-workspace>/embed/dashboardsv3/<dashboard-id>?o=<workspace-id>"
